Repository openstack-k8s-operators/ovs-operator, pull requests merged in 2023-02, with the labels that each got.

#48 Gracefully stop ovsdb-server process
  templates/bin/start-ovsdb-server.sh
Labels: lgtm, ok-to-test, approved

#53 Gracefully terminate containers on pod delete
  pkg/ovs/daemonset.go
  templates/bin/start-ovsdb-server.sh
Labels: needs-ok-to-test, lgtm, approved

#57 Use time.Duration for timeout
  controllers/ovs_controller.go
  go.mod
  go.sum
Labels: lgtm, approved

#49 Upgrade to golang 1.19/SDK 1.26
  .github/workflows/build-ovs-operator.yaml
  .github/workflows/golangci-lint.yaml
  Dockerfile
  Makefile
  api/bases/ovs.openstack.org_ovs.yaml
  api/go.mod
  config/crd/bases/ovs.openstack.org_ovs.yaml
  go.mod
Labels: lgtm, approved

#58 Return error in ConfigMap creation
  controllers/ovs_controller.go
Labels: lgtm, approved

#59 Make start-ovsdb-server.sh executable.
  templates/bin/start-ovsdb-server.sh
Labels: lgtm, ok-to-test, approved

#60 Add basic KUTTL tests for ovs operator
  config/samples/ovs_v1beta1_ovs.yaml
  kuttl-test.yaml
  tests/kuttl/common/assert_sample_deployment.yaml
  tests/kuttl/common/cleanup-ovs.yaml
  tests/kuttl/common/deploy_ovs.yaml
  tests/kuttl/common/errors_cleanup_ovs.yaml
  tests/kuttl/tests/ovs_deploy/01-assert.yaml
  tests/kuttl/tests/ovs_deploy/01-deploy-ovs.yaml
  tests/kuttl/tests/ovs_deploy/02-errors.yaml
  tests/kuttl/tests/ovs_deploy/02-scale-down-pods-ovs.yaml
  tests/kuttl/tests/ovs_deploy/03-cleanup-ovs.yaml
  tests/kuttl/tests/ovs_deploy/03-errors.yaml
Labels: lgtm, approved

#62 Drop paths-ignore from build operator workflow
  .github/workflows/build-ovs-operator.yaml
Labels: lgtm, approved

#65 Added ci-operator.yaml file
  .ci-operator.yaml
Labels: lgtm, approved

#54 Fix wait_for_ovsdb_server routine for ovn-controller container
  templates/bin/init.sh
Labels: lgtm, ok-to-test, approved

#61 Pass GITHUB_TOKEN to install_kustomize.sh to avoid rate-limit
  .github/workflows/build-ovs-operator.yaml
Labels: lgtm, approved
